language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository

script:
  - ./gradlew clean build jacocoDebugReport coveralls -Dscan --configure-on-demand --parallel --stacktrace

branches:
  except:
    - gh-pages

sudo: false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
