language: android

matrix:
  include:
    - dist: trusty
      jdk: oraclejdk8

install:
  # Download SDK
  - yes | sdkmanager "tools" &>/dev/null
  - yes | sdkmanager "platform-tools" &>/dev/null
  - yes | sdkmanager "platforms;android-28" &>/dev/null
  # Update remaining dependencies and accept licenses
  - yes | sdkmanager --update &>/dev/null
  - yes | sdkmanager --licenses &>/dev/null

script:
  - ./gradlew clean testDebug lintDebug jacocoDebugReport coveralls -Pci -s --scan

branches:
  except:
    - gh-pages

sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
