environment:
  ANDROID_HOME: "C:\\android-sdk-windows"
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

clone_folder: "C:\\projects\\android-gradle-java-app-template"

init:
  - cd \
  - appveyor DownloadFile http://dl.google.com/android/android-sdk_r24.4.1-windows.zip
  - 7z x android-sdk_r24.4.1-windows.zip > nul
  - cd C:\projects\android-gradle-java-app-template

install:
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter android-23
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter platform-tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter tools
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter build-tools-23.0.3
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter extra-google-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter extra-google-google_play_services
  - echo y | "%ANDROID_HOME%\tools\android.bat" update sdk --no-ui --all --filter extra-android-support

build_script:
# - del /F /Q "%USERPROFILE%\.gradle\caches\modules-2\modules-2.lock" 2>NUL
  - gradlew.bat clean assembleDebug testDebug jacocoDebugReport coveralls -Dreceipt -s

artifacts:
  - path: "build\\reports\\"

cache:
  - "%USERPROFILE%\\.m2"
  - "%USERPROFILE%\\.gradle"
  - "%USERPROFILE%\\.gradle\\caches\\"
  - "%USERPROFILE%\\.gradle\\wrapper\\"
